name: action

on: 
    - push 
    - pull_request
   
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and tests
        run: |
          poetry add -G dev flake8
          make lint
          poetry add -G dev pytest
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true

