name: file

on: push 
   
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Install and run pytest
        run: |
          pip install pytest 
          pytest  
      - name: Install and run flake8
        run: |
          pip install flake8 
          flake8 gendiff
          flake8 tests
       
         
